export const CHANGE_MESSAGE = 'CHANGE_MESSAGE';
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const DELETE_PRODUCT_IN_CARD = 'DELETE_PRODUCT_IN_CARD';
export const UPDATE_QUANTITY_PRODUCT_IN_CARD = 'UPDATE_QUANTITY_PRODUCT_IN_CARD';