export const CHAO_MUNG_BAN_DEN_VOI_WEBSITE = 'CHAO_MUNG_BAN_DEN_VOI_WEBSITE';
export const THEM_SAN_PHAM_THANH_CONG = 'THEM_SAN_PHAM_THANH_CONG';
export const XOA_SAN_PHAM_THANH_CONG = 'XOA_SAN_PHAM_THANH_CONG';
export const SUA_SO_LUONG_SAN_PHAM_THANH_CONG = 'SUA_SO_LUONG_SAN_PHAM_THANH_CONG';